FROM rasa/rasa:3.6.21-full

WORKDIR /app

COPY --chown=1001:0 credentials.yml endpoints.yml /app/
COPY --chown=1001:0 models/20250622-222835-amiable-rotation.tar.gz /app/models/model.tar.gz

ENV HF_HOME=/tmp/huggingface
ENV TRANSFORMERS_CACHE=/tmp/huggingface
ENV SANIC_WORKERS=1

EXPOSE 10000

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["exec rasa run --model /app/models/model.tar.gz --credentials /app/credentials.yml --endpoints /app/endpoints.yml --interface 0.0.0.0 --port \"${PORT:-10000}\" --cors \"$FRONTEND_ORIGIN\""]